// Generated by `make ports` from internal/config/ports.go. Do not edit.
//
// The server's own default, which is what a bare LAN address typed without a
// port has to mean. It is generated rather than written here so that moving the
// server's port cannot leave the app guessing the old one.
export const DEFAULT_SERVER_PORT = '39170';
