#!/usr/bin/env node
// Generates mobile/src/design/tokens.ts from web/src/app.css so the mobile
// palette can never drift from the web palette that check-contrast.py gates.
// Parses the :root block and every `.dark { … }` block (app.css has two: a
// short one that only overrides --scrim/--shadow/--shadow-strong for the
// dark theme's floating chrome, and the real palette block that defines
// --background and the rest of the color overrides). Both are merged — they
// define disjoint property sets, exactly as the CSS cascade would combine
// them — so the dark theme keeps its own scrim/shadow AND its own palette.
// camelCases --token-name to tokenName.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const cssPath = resolve(here, '../../web/src/app.css');
const outPath = resolve(here, '../src/design/tokens.ts');

const css = await readFile(cssPath, 'utf8');

function firstBlock(selectorRegex) {
  const m = css.match(selectorRegex);
  if (!m) throw new Error(`sync-tokens: could not find block for ${selectorRegex}`);
  return m[1];
}

// There is exactly one :root { … } block: the light palette plus the
// shared motion/font tokens.
const rootBody = firstBlock(/:root\s*\{([\s\S]*?)\n\}/);

// Concatenate every top-level `.dark { … }` block's body — not just the
// first, and not by guessing which one carries --background via a single
// greedy/lazy regex spanning both blocks (fragile: it happens to work today
// only because nothing between the two blocks contains a stray `}`, and it
// silently drops tokens if the blocks are ever reordered or a third `.dark`
// block is added). Instead, collect all `.dark` blocks explicitly.
const darkBlockRe = /\.dark\s*\{([\s\S]*?)\n\}/g;
let darkBody = '';
let dm;
let darkBlockCount = 0;
while ((dm = darkBlockRe.exec(css))) {
  darkBody += `\n${dm[1]}`;
  darkBlockCount += 1;
}
if (darkBlockCount === 0) {
  throw new Error('sync-tokens: could not find any .dark { … } block');
}
if (!/--background\s*:/.test(darkBody)) {
  throw new Error('sync-tokens: merged .dark blocks do not define --background — check app.css structure');
}

function parse(body) {
  // Strip CSS comments first. app.css has design-commentary comments that
  // reference token names in prose (e.g. "Deliberately NOT --primary: as the
  // button fill it would compete..."), and those read as valid
  // `--name: value;` declarations to a naive regex — including swallowing
  // the *next real* declaration into the comment-derived value, since `;`
  // inside the comment doesn't terminate until the following statement's
  // semicolon. Removing comments before matching avoids that entirely.
  const withoutComments = body.replace(/\/\*[\s\S]*?\*\//g, '');
  const out = {};
  const re = /--([a-z0-9-]+)\s*:\s*([^;]+);/gi;
  let m;
  while ((m = re.exec(withoutComments))) {
    const name = m[1].replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
    out[name] = m[2].trim();
  }
  return out;
}

const light = parse(rootBody);
const dark = { ...light, ...parse(darkBody) }; // dark overrides light, keeps light-only tokens (motion/fonts)

const banner = `// GENERATED by mobile/scripts/sync-tokens.mjs from web/src/app.css.\n// Do NOT edit by hand. Run: npm run sync-tokens\n`;
// darkTokens is intentionally NOT typed `typeof lightTokens`: with `as const`
// on lightTokens, that type pins each key to its specific light-mode literal
// value (e.g. background: "#f2efe8"), which no dark-mode object with
// different literal values could ever satisfy. `Record<TokenName, string>`
// keeps the key set exact while widening values to `string`.
const body =
  `${banner}\nexport const lightTokens = ${JSON.stringify(light, null, 2)} as const;\n\n` +
  `export type TokenName = keyof typeof lightTokens;\n\n` +
  `export const darkTokens: Record<TokenName, string> = ${JSON.stringify(dark, null, 2)};\n`;

await writeFile(outPath, body);
console.log(`sync-tokens: wrote ${Object.keys(light).length} tokens (from ${darkBlockCount} .dark block(s)) to ${outPath}`);
