// GENERATED by mobile/scripts/sync-tokens.mjs from web/src/app.css.
// Do NOT edit by hand. Run: npm run sync-tokens

export const galleryTokens = {
  "mediaRadius": 8,
  "collectionRadius": 12,
  "mediaGap": 4,
  "memoryWidth": 132,
  "memoryHeight": 176
} as const;
