#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = resolve(root, 'design/tokens.json');
const cssPath = resolve(root, 'web/src/app.css');
const mobilePath = resolve(root, 'mobile/src/design/tokens.ts');
const start = '/* GENERATED DESIGN TOKENS:START — run `npm run sync-design` in web or mobile. */';
const end = '/* GENERATED DESIGN TOKENS:END */';

const source = JSON.parse(await readFile(sourcePath, 'utf8'));
const toKebab = (name) =>
  name
    .replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)
    .replace(/([a-z])([0-9])/g, '$1-$2');
const declarations = (values) =>
  Object.entries(values).map(([name, value]) => `  --${toKebab(name)}: ${value};`).join('\n');
const metricDeclarations = (values, path = []) =>
  Object.entries(values)
    .flatMap(([name, value]) =>
      typeof value === 'object'
        ? metricDeclarations(value, [...path, name])
        : [`  --ds-${[...path, name].map(toKebab).join('-')}: ${value}px;`]
    )
    .join('\n');

const light = { ...source.shared, ...source.light };
const dark = { ...source.shared, ...source.light, ...source.dark };
const cssBlock = `${start}
:root {
${declarations(light)}
${metricDeclarations(source.metrics)}
}
.dark {
${declarations(source.dark)}
}
${end}`;

const css = await readFile(cssPath, 'utf8');
const from = css.indexOf(start);
const through = css.indexOf(end);
if (from < 0 || through < 0 || through < from) {
  throw new Error('generate-design: token markers are missing or out of order in web/src/app.css');
}
await writeFile(cssPath, `${css.slice(0, from)}${cssBlock}${css.slice(through + end.length)}`);

const banner = `// GENERATED by scripts/generate-design.mjs from design/tokens.json.\n// Do not edit by hand. Run: npm run sync-design\n`;
const mobile = `${banner}
export const lightTokens = ${JSON.stringify(light, null, 2)} as const;

export type TokenName = keyof typeof lightTokens;

export const darkTokens: Record<TokenName, string> = ${JSON.stringify(dark, null, 2)};

export const designMetrics = ${JSON.stringify(source.metrics, null, 2)} as const;
`;
await writeFile(mobilePath, mobile);

console.log(`generate-design: wrote ${Object.keys(light).length} tokens and shared metrics`);
