//go:build ignore

// Command gen_ports writes the port block in internal/config/ports.go out to
// the surfaces that cannot import Go.
//
// Run via `make ports` (and therefore `make gen` / `make check-gen`). Editing
// either output by hand fails the build, like every other generated artifact.
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/kuraki-app/kuraki/internal/config"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		fail(err)
	}

	env := fmt.Sprintf(`# Generated by `+"`make ports`"+` from internal/config/ports.go. Do not edit.
#
# Sourced by scripts/dev.sh, and parsed by web/vite.config.ts,
# web/playwright.config.ts and web/e2e/server.mjs. The Go server owns these
# numbers; everything else reads them from here.
KURAKI_DEFAULT_PORT=%d
KURAKI_PORT=%d
KURAKI_WEB_PORT=%d
KURAKI_MOBILE_PORT=%d
KURAKI_E2E_PORT=%d
`, config.DefaultServerPort, config.DevServerPort, config.DevWebPort, config.DevMobilePort, config.E2EPort)
	write(filepath.Join(root, "ports.env"), env)

	ts := fmt.Sprintf(`// Generated by `+"`make ports`"+` from internal/config/ports.go. Do not edit.
//
// The server's own default, which is what a bare LAN address typed without a
// port has to mean. It is generated rather than written here so that moving the
// server's port cannot leave the app guessing the old one.
export const DEFAULT_SERVER_PORT = '%d';
`, config.DefaultServerPort)
	write(filepath.Join(root, "mobile", "src", "design", "ports.ts"), ts)
}

func write(path, body string) {
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		fail(err)
	}
	fmt.Println("gen-ports: wrote", path)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen-ports:", err)
	os.Exit(1)
}
